name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[deploy-backend]')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build project using Maven
      run: mvn clean package -DskipTests

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        script: |
          set -x  # Enable debugging
          sudo pkill -9 -f 'HRIS_job_portal.jar' || true  # Force stop only the Spring Boot app
          cd /home/ubuntu/app/
          rm -rf *  # Clear the directory
          sudo fallocate -l 1G /swapfile  # Add swap memory if necessary
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

    - name: Transfer Jar File to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        source: target/your-spring-boot-app.jar
        target: /home/ubuntu/app/your-spring-boot-app.jar

    - name: Copy .env file to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        script: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > /home/ubuntu/app/.env

    - name: Start Spring Boot App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/app/
          sleep 10  # Delay before starting the app
          nohup java -jar your-spring-boot-app.jar &
