name: Deploy GitHub Release to GitHub Pages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create environment directory
        run: mkdir -p client/src/environments

      - name: Setup environment variables for production
        run: echo "${{ secrets.ENV_FILE_PROD_CONTENT }}" > client/src/environments/environment.ts

      - name: Setup environment variables for development
        run: echo "${{ secrets.ENV_FILE_DEV_CONTENT }}" > client/src/environments/environment.development.ts
      
      - name: Install dependencies
        run: |
          cd client
          npm install --force
      
      - name: Build frontend
        run: |
          cd client
          npm npm run build -- --output-path=dist --base-href="/Public_Job_Bord/v${{ github.event.release.tag_name }}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          
          destination_dir: ${{ github.event.release.tag_name }}
